In [12]:
import pandas as pd
from zipfile import ZipFile
from io import BytesIO
import requests
day_import = pd.read_csv('day.csv')
hour_import = pd.read_csv('hour.csv')




url = 'https://s3.amazonaws.com/capitalbikeshare-data/202308-capitalbikeshare-tripdata.zip'
r = requests.get(url)
buf1 = BytesIO(r.content)
with ZipFile(buf1, "r") as f:
    for name in f.namelist():
        if name.endswith('.csv'):
            with f.open(name) as zd:
                df = pd.read_csv(zd)
            print(df)
            break

                 ride_id  rideable_type           started_at  \
0       D88F352076694FFC   classic_bike  2023-08-03 17:33:41
1       6B733406B1E19446   classic_bike  2023-08-16 08:19:26
2       56145CE76A7B5A66   classic_bike  2023-08-25 08:19:20
3       11B7E5D90AE9DBE5   classic_bike  2023-08-15 17:56:22
4       D934138EBBF5BE96   classic_bike  2023-08-12 15:38:38
...                  ...            ...                  ...
470127  882A9882FE149C4E  electric_bike  2023-08-14 06:36:54
470128  7EA83543167EEFAF  electric_bike  2023-08-04 16:01:20
470129  CF6F626FF38A2F01  electric_bike  2023-08-30 17:21:18
470130  1B3EF9D0CF8062A1  electric_bike  2023-08-28 08:33:48
470131  81C639463D62B4AB  electric_bike  2023-08-12 16:15:40

                   ended_at             start_station_name  start_station_id  \
0       2023-08-03 18:03:07  5th St & Massachusetts Ave NW           31265.0
1       2023-08-16 08:34:07                  5th & K St NW           31600.0
2       2023-08-25 08:37:11                  5th & K St NW           31600.0
3       2023-08-15 18:13:58                23rd & E St NW            31260.0
4       2023-08-12 15:46:22                  5th & K St NW           31600.0
...                     ...                            ...               ...
470127  2023-08-14 06:38:15                            NaN               NaN
470128  2023-08-04 16:01:34                            NaN               NaN
470129  2023-08-30 17:44:32                            NaN               NaN
470130  2023-08-28 08:52:07                            NaN               NaN
470131  2023-08-12 16:24:06                            NaN               NaN

             end_station_name  end_station_id  start_lat  start_lng  \
0       20th & Columbia Rd NW         31133.0  38.900930 -77.018677
1             23rd & E St NW          31260.0  38.903040 -77.019027
2             23rd & E St NW          31260.0  38.903040 -77.019027
3               5th & K St NW         31600.0  38.896104 -77.049882
4              11th & O St NW         31286.0  38.903040 -77.019027
...                       ...             ...        ...        ...
470127  20th & Columbia Rd NW         31133.0  38.920000 -77.050000
470128        23rd & E St NW          31260.0  38.900000 -77.050000
470129  20th & Columbia Rd NW         31133.0  38.910000 -77.030000
470130         15th & L St NW         31276.0  38.900000 -76.980000
470131  20th & Columbia Rd NW         31133.0  38.910000 -77.020000

          end_lat    end_lng member_casual
0       38.918036 -77.045487        member
1       38.896104 -77.049882        member
2       38.896104 -77.049882        member
3       38.903040 -77.019027        member
4       38.908431 -77.027088        member
...           ...        ...           ...
470127  38.918036 -77.045487        member
470128  38.896104 -77.049882        member
470129  38.918036 -77.045487        casual
470130  38.903649 -77.034918        casual
470131  38.918036 -77.045487        casual

[470132 rows x 13 columns]

In [13]:
day=day_import.copy()

def get_infos(df):
    print('Shape:\n',df.shape, '\n\n')
    print('Info:\n',df.info(), '\n\n')
    print('Desctibe:\n',df.describe(), '\n\n')
    print('Head:\n',df.head(), '\n\n')


get_infos(day)

Shape:
 (731, 16)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   dteday      731 non-null    object
 2   season      731 non-null    int64
 3   yr          731 non-null    int64
 4   mnth        731 non-null    int64
 5   holiday     731 non-null    int64
 6   weekday     731 non-null    int64
 7   workingday  731 non-null    int64
 8   weathersit  731 non-null    int64
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  casual      731 non-null    int64
 14  registered  731 non-null    int64
 15  cnt         731 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.5+ KB
Info:
 None


Desctibe:
           instant      season          yr        mnth     holiday     weekday  \
count  731.000000  731.000000  731.000000  731.000000  731.000000  731.000000
mean   366.000000    2.496580    0.500684    6.519836    0.028728    2.997264
std    211.165812    1.110807    0.500342    3.451913    0.167155    2.004787
min      1.000000    1.000000    0.000000    1.000000    0.000000    0.000000
25%    183.500000    2.000000    0.000000    4.000000    0.000000    1.000000
50%    366.000000    3.000000    1.000000    7.000000    0.000000    3.000000
75%    548.500000    3.000000    1.000000   10.000000    0.000000    5.000000
max    731.000000    4.000000    1.000000   12.000000    1.000000    6.000000

       workingday  weathersit        temp       atemp         hum   windspeed  \
count  731.000000  731.000000  731.000000  731.000000  731.000000  731.000000
mean     0.683995    1.395349    0.495385    0.474354    0.627894    0.190486
std      0.465233    0.544894    0.183051    0.162961    0.142429    0.077498
min      0.000000    1.000000    0.059130    0.079070    0.000000    0.022392
25%      0.000000    1.000000    0.337083    0.337842    0.520000    0.134950
50%      1.000000    1.000000    0.498333    0.486733    0.626667    0.180975
75%      1.000000    2.000000    0.655417    0.608602    0.730209    0.233214
max      1.000000    3.000000    0.861667    0.840896    0.972500    0.507463

            casual   registered          cnt
count   731.000000   731.000000   731.000000
mean    848.176471  3656.172367  4504.348837
std     686.622488  1560.256377  1937.211452
min       2.000000    20.000000    22.000000
25%     315.500000  2497.000000  3152.000000
50%     713.000000  3662.000000  4548.000000
75%    1096.000000  4776.500000  5956.000000
max    3410.000000  6946.000000  8714.000000


Head:
    instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0
1        2  2011-01-02       1   0     1        0        0           0
2        3  2011-01-03       1   0     1        0        1           1
3        4  2011-01-04       1   0     1        0        2           1
4        5  2011-01-05       1   0     1        0        3           1

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654
1           2  0.363478  0.353739  0.696087   0.248539     131         670
2           1  0.196364  0.189405  0.437273   0.248309     120        1229
3           1  0.200000  0.212122  0.590435   0.160296     108        1454
4           1  0.226957  0.229270  0.436957   0.186900      82        1518

    cnt
0   985
1   801
2  1349
3  1562
4  1600

In [14]:
hour=hour_import.copy()
get_infos(hour)

Shape:
 (17379, 17)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB
Info:
 None


Desctibe:
           instant        season            yr          mnth            hr  \
count  17379.0000  17379.000000  17379.000000  17379.000000  17379.000000
mean    8690.0000      2.501640      0.502561      6.537775     11.546752
std     5017.0295      1.106918      0.500008      3.438776      6.914405
min        1.0000      1.000000      0.000000      1.000000      0.000000
25%     4345.5000      2.000000      0.000000      4.000000      6.000000
50%     8690.0000      3.000000      1.000000      7.000000     12.000000
75%    13034.5000      3.000000      1.000000     10.000000     18.000000
max    17379.0000      4.000000      1.000000     12.000000     23.000000

            holiday       weekday    workingday    weathersit          temp  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000
mean       0.028770      3.003683      0.682721      1.425283      0.496987
std        0.167165      2.005771      0.465431      0.639357      0.192556
min        0.000000      0.000000      0.000000      1.000000      0.020000
25%        0.000000      1.000000      0.000000      1.000000      0.340000
50%        0.000000      3.000000      1.000000      1.000000      0.500000
75%        0.000000      5.000000      1.000000      2.000000      0.660000
max        1.000000      6.000000      1.000000      4.000000      1.000000

              atemp           hum     windspeed        casual    registered  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000
mean       0.475775      0.627229      0.190098     35.676218    153.786869
std        0.171850      0.192930      0.122340     49.305030    151.357286
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.333300      0.480000      0.104500      4.000000     34.000000
50%        0.484800      0.630000      0.194000     17.000000    115.000000
75%        0.621200      0.780000      0.253700     48.000000    220.000000
max        1.000000      1.000000      0.850700    367.000000    886.000000

                cnt
count  17379.000000
mean     189.463088
std      181.387599
min        1.000000
25%       40.000000
50%      142.000000
75%      281.000000
max      977.000000


Head:
    instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0
1        2  2011-01-01       1   0     1   1        0        6           0
2        3  2011-01-01       1   0     1   2        0        6           0
3        4  2011-01-01       1   0     1   3        0        6           0
4        5  2011-01-01       1   0     1   4        0        6           0

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt
0           1  0.24  0.2879  0.81        0.0       3          13   16
1           1  0.22  0.2727  0.80        0.0       8          32   40
2           1  0.22  0.2727  0.80        0.0       5          27   32
3           1  0.24  0.2879  0.75        0.0       3          10   13
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [15]:
tripdata=trip_import.copy()
get_infos(tripdata)
tripdata.head()

NameError: name 'trip_import' is not defined