In [7]:
import pandas as pd
day_import = pd.read_csv('day.csv')
hour_import = pd.read_csv('hour.csv')
trip_import = pd.read_csv('202310-tripdata.csv')

In [8]:
day=day_import.copy()

def get_infos(df):
    print('Shape:\n',df.shape, '\n\n')
    print('Info:\n',df.info(), '\n\n')
    print('Desctibe:\n',df.describe(), '\n\n')
    print('Head:\n',df.head(), '\n\n')


get_infos(day)

Shape:
 (731, 16)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   dteday      731 non-null    object
 2   season      731 non-null    int64
 3   yr          731 non-null    int64
 4   mnth        731 non-null    int64
 5   holiday     731 non-null    int64
 6   weekday     731 non-null    int64
 7   workingday  731 non-null    int64
 8   weathersit  731 non-null    int64
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  casual      731 non-null    int64
 14  registered  731 non-null    int64
 15  cnt         731 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.5+ KB
Info:
 None


Desctibe:
           instant      season          yr        mnth     holiday     weekday  \
count  731.000000  731.000000  731.000000  731.000000  731.000000  731.000000
mean   366.000000    2.496580    0.500684    6.519836    0.028728    2.997264
std    211.165812    1.110807    0.500342    3.451913    0.167155    2.004787
min      1.000000    1.000000    0.000000    1.000000    0.000000    0.000000
25%    183.500000    2.000000    0.000000    4.000000    0.000000    1.000000
50%    366.000000    3.000000    1.000000    7.000000    0.000000    3.000000
75%    548.500000    3.000000    1.000000   10.000000    0.000000    5.000000
max    731.000000    4.000000    1.000000   12.000000    1.000000    6.000000

       workingday  weathersit        temp       atemp         hum   windspeed  \
count  731.000000  731.000000  731.000000  731.000000  731.000000  731.000000
mean     0.683995    1.395349    0.495385    0.474354    0.627894    0.190486
std      0.465233    0.544894    0.183051    0.162961    0.142429    0.077498
min      0.000000    1.000000    0.059130    0.079070    0.000000    0.022392
25%      0.000000    1.000000    0.337083    0.337842    0.520000    0.134950
50%      1.000000    1.000000    0.498333    0.486733    0.626667    0.180975
75%      1.000000    2.000000    0.655417    0.608602    0.730209    0.233214
max      1.000000    3.000000    0.861667    0.840896    0.972500    0.507463

            casual   registered          cnt
count   731.000000   731.000000   731.000000
mean    848.176471  3656.172367  4504.348837
std     686.622488  1560.256377  1937.211452
min       2.000000    20.000000    22.000000
25%     315.500000  2497.000000  3152.000000
50%     713.000000  3662.000000  4548.000000
75%    1096.000000  4776.500000  5956.000000
max    3410.000000  6946.000000  8714.000000


Head:
    instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0
1        2  2011-01-02       1   0     1        0        0           0
2        3  2011-01-03       1   0     1        0        1           1
3        4  2011-01-04       1   0     1        0        2           1
4        5  2011-01-05       1   0     1        0        3           1

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654
1           2  0.363478  0.353739  0.696087   0.248539     131         670
2           1  0.196364  0.189405  0.437273   0.248309     120        1229
3           1  0.200000  0.212122  0.590435   0.160296     108        1454
4           1  0.226957  0.229270  0.436957   0.186900      82        1518

    cnt
0   985
1   801
2  1349
3  1562
4  1600

In [9]:
hour=hour_import.copy()
get_infos(hour)

Shape:
 (17379, 17)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB
Info:
 None


Desctibe:
           instant        season            yr          mnth            hr  \
count  17379.0000  17379.000000  17379.000000  17379.000000  17379.000000
mean    8690.0000      2.501640      0.502561      6.537775     11.546752
std     5017.0295      1.106918      0.500008      3.438776      6.914405
min        1.0000      1.000000      0.000000      1.000000      0.000000
25%     4345.5000      2.000000      0.000000      4.000000      6.000000
50%     8690.0000      3.000000      1.000000      7.000000     12.000000
75%    13034.5000      3.000000      1.000000     10.000000     18.000000
max    17379.0000      4.000000      1.000000     12.000000     23.000000

            holiday       weekday    workingday    weathersit          temp  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000
mean       0.028770      3.003683      0.682721      1.425283      0.496987
std        0.167165      2.005771      0.465431      0.639357      0.192556
min        0.000000      0.000000      0.000000      1.000000      0.020000
25%        0.000000      1.000000      0.000000      1.000000      0.340000
50%        0.000000      3.000000      1.000000      1.000000      0.500000
75%        0.000000      5.000000      1.000000      2.000000      0.660000
max        1.000000      6.000000      1.000000      4.000000      1.000000

              atemp           hum     windspeed        casual    registered  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000
mean       0.475775      0.627229      0.190098     35.676218    153.786869
std        0.171850      0.192930      0.122340     49.305030    151.357286
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.333300      0.480000      0.104500      4.000000     34.000000
50%        0.484800      0.630000      0.194000     17.000000    115.000000
75%        0.621200      0.780000      0.253700     48.000000    220.000000
max        1.000000      1.000000      0.850700    367.000000    886.000000

                cnt
count  17379.000000
mean     189.463088
std      181.387599
min        1.000000
25%       40.000000
50%      142.000000
75%      281.000000
max      977.000000


Head:
    instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0
1        2  2011-01-01       1   0     1   1        0        6           0
2        3  2011-01-01       1   0     1   2        0        6           0
3        4  2011-01-01       1   0     1   3        0        6           0
4        5  2011-01-01       1   0     1   4        0        6           0

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt
0           1  0.24  0.2879  0.81        0.0       3          13   16
1           1  0.22  0.2727  0.80        0.0       8          32   40
2           1  0.22  0.2727  0.80        0.0       5          27   32
3           1  0.24  0.2879  0.75        0.0       3          10   13
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [10]:
tripdata=trip_import.copy()
get_infos(tripdata)
tripdata.head()

Shape:
 (491084, 13)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491084 entries, 0 to 491083
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             491084 non-null  object
 1   rideable_type       491084 non-null  object
 2   started_at          491084 non-null  object
 3   ended_at            491084 non-null  object
 4   start_station_name  434475 non-null  object
 5   start_station_id    434475 non-null  float64
 6   end_station_name    431026 non-null  object
 7   end_station_id      431026 non-null  float64
 8   start_lat           491084 non-null  float64
 9   start_lng           491084 non-null  float64
 10  end_lat             490538 non-null  float64
 11  end_lng             490538 non-null  float64
 12  member_casual       491084 non-null  object
dtypes: float64(6), object(7)
memory usage: 48.7+ MB
Info:
 None


Desctibe:
        start_station_id  end_station_id      start_lat      start_lng  \
count     434475.000000   431026.000000  491084.000000  491084.000000
mean       31372.701589    31374.750078      38.905071     -77.032142
std          282.295892      283.708393       0.027203       0.034206
min        30200.000000    30200.000000      38.780000     -77.390000
25%        31208.000000    31212.000000      38.893438     -77.044400
50%        31281.000000    31281.000000      38.903819     -77.030000
75%        31609.000000    31610.000000      38.917036     -77.012785
max        33200.000000    33200.000000      39.140000     -76.825535

             end_lat        end_lng
count  490538.000000  490538.000000
mean       38.904184     -77.031853
std         0.027051       0.034100
min        38.710000     -77.450000
25%        38.892934     -77.044600
50%        38.903040     -77.030000
75%        38.915544     -77.012289
max        39.140000     -76.825535


Head:
             ride_id  rideable_type           started_at             ended_at  \
0  CB181909FC05004F  electric_bike  2023-10-29 09:10:14  2023-10-29 09:25:19
1  77832F0C46F1B308   classic_bike  2023-10-28 12:26:17  2023-10-28 12:35:41
2  777600C797581E8F   classic_bike  2023-10-01 10:18:50  2023-10-01 10:51:19
3  8A8C4C384180159A   classic_bike  2023-10-05 10:40:56  2023-10-05 11:27:40
4  C3CD670D215D5202   classic_bike  2023-10-23 18:30:45  2023-10-23 18:43:23

                             start_station_name  start_station_id  \
0                          11th & Clifton St NW           31136.0
1                          11th & Clifton St NW           31136.0
2                     12th St & New York Ave NW           31670.0
3            36th & Calvert St NW / Glover Park           31304.0
4  W&OD Trail/Sunset Hills Rd & Isaac Newton Sq           32220.0

                              end_station_name  end_station_id  start_lat  \
0               L'Enfant Plaza / 7th & C St SW         31218.0  38.922089
1         Massachusetts Ave & Dupont Circle NW         31200.0  38.922324
2         Massachusetts Ave & Dupont Circle NW         31200.0  38.901104
3         Massachusetts Ave & Dupont Circle NW         31200.0  38.922581
4  W&OD Trail & Explorer St/Reston Bus Station         32214.0  38.951443

   start_lng    end_lat    end_lng member_casual
0 -77.027172  38.886266 -77.022241        member
1 -77.027086  38.910100 -77.044400        member
2 -77.028061  38.910100 -77.044400        casual
3 -77.070334  38.910100 -77.044400        casual
4 -77.340377  38.957037 -77.359718        casual

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CB181909FC05004F,electric_bike,2023-10-29 09:10:14,2023-10-29 09:25:19,11th & Clifton St NW,31136.0,L'Enfant Plaza / 7th & C St SW,31218.0,38.922089,-77.027172,38.886266,-77.022241,member
1,77832F0C46F1B308,classic_bike,2023-10-28 12:26:17,2023-10-28 12:35:41,11th & Clifton St NW,31136.0,Massachusetts Ave & Dupont Circle NW,31200.0,38.922324,-77.027086,38.910100,-77.044400,member
2,777600C797581E8F,classic_bike,2023-10-01 10:18:50,2023-10-01 10:51:19,12th St & New York Ave NW,31670.0,Massachusetts Ave & Dupont Circle NW,31200.0,38.901104,-77.028061,38.910100,-77.044400,casual
3,8A8C4C384180159A,classic_bike,2023-10-05 10:40:56,2023-10-05 11:27:40,36th & Calvert St NW / Glover Park,31304.0,Massachusetts Ave & Dupont Circle NW,31200.0,38.922581,-77.070334,38.910100,-77.044400,casual
4,C3CD670D215D5202,classic_bike,2023-10-23 18:30:45,2023-10-23 18:43:23,W&OD Trail/Sunset Hills Rd & Isaac Newton Sq,32220.0,W&OD Trail & Explorer St/Reston Bus Station,32214.0,38.951443,-77.340377,38.957037,-77.359718,casual